blogMS/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [ 
    path('entradas/', views.EntryListView.as_view(), name='entry-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entry-detail'),  
]

blogMS/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('quienes-somos', views.quienesSomosView.as_view(), name='quienes-somos'),  
    path('contacto', views.ContactoView.as_view(), name='contacto'),  
    path('', views.HomePageView.as_view(), name='index'),  
    path('register-suscripcion', views.SuscribersCreateView.as_view(), name='add-suscripcion'),  
    path('contact', views.contacto, name='add-contact'),   
]

blogMS/blogMS/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),   
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls de terceros
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] 

if settings.DEBUG:
    urlpatterns_main += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns_main += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns_main += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

# objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}
urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemap.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blogMS/applications/home/models.py
from django.db import models

# apps terceros
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    """ Modelo de pagina de Home """
    title = models.CharField('nombre', max_length=30)
    descripcion = models.TextField()
    about_title = models.CharField('Proximo Evento', max_length=50)
    about_text = models.TextField('Nombre del Evento')
    contact_email = models.EmailField('email de contacto', blank=True, null=True)
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Home')
    in_home = models.BooleanField(default=False)
    phone = models.CharField('Telefono de contacto', max_length=20)
    
    class Meta:
        verbose_name = 'Home'
        verbose_name_plural = 'Home'
        
    def __str__(self):
        
        return self.title
    
    
class Suscribers(TimeStampedModel):
    """ Modelo de Suscriptores """
    email = models.EmailField()
    
    class Meta:
        verbose_name = 'Susciptor'
        verbose_name_plural = 'Suscriptores'
        
    def __str__(self):
        return self.email
        

class Contact(TimeStampedModel):
    """ Modelo de Contactos """
    asunto = models.CharField(max_length=250, default="")
    email = models.EmailField()
    message = models.TextField()
    
    
    class Meta:
        verbose_name = 'Mensaje'
        verbose_name_plural = 'Mensajes'
        
    def __str__(self):
        return self.asunto + ' ---> ' + self.email

blogMS/applications/home/forms.py
from django import forms
from .models import Suscribers, Contact

class SuscribersForm(forms.ModelForm):
    class Meta:
        model = Suscribers
        fields = ( 'email',)
        
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'correo electrónico...'
            }),
        }
    
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')

blogMS/applications/home/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import (TemplateView, CreateView)
from applications.entrada.models import Entry
from .models import Home, Contact
from .forms import SuscribersForm, ContactForm

class HomePageView(TemplateView):
    template_name = "home/index.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        # carga del texto en home quienes somos
        context["home"] = Home.objects.latest('created')
        # contexto de portada
        context["portada"] = Entry.objects.entrada_en_portada()
        # contexto para los articulos en home
        context["entradas_home"] = Entry.objects.entradas_en_home()
        # contexto para las entradas recientes
        context["entradas_recientes"] = Entry.objects.entradas_recientes()
        # enviando formulario de suscripcion
       
        
        context["form"] = SuscribersForm
        
        return context
    

class SuscribersCreateView(CreateView):
   form_class = SuscribersForm
   success_url = '.'
   

def contacto(request):
    
    if request.method == "POST":
        print(1)
        subject = request.POST["full_name"]
        email = request.POST["email"]
        message = request.POST["messagge"]
        email_from = settings.EMAIL_HOST_USER
        print(2)
        recipient_list = ["mujeressembradorasvidanueva@outlook.com"]
        print(3)
        fulldata = "asunto:" + subject + "\nemail: " + email + "\nmessagge: " + message 

        Contact.objects.create(
            asunto = subject,
            email = email,
            message = message
        )
        print(4)
        send_mail("Correo Recibido desde www.MujeresSembradorasInternacional.com", fulldata, email_from, recipient_list)
       
        return render(request, "contact.html") 
    else:
        return redirect("home_app:index")
        

    
class quienesSomosView(TemplateView):
    template_name = "home/quienes-somos.html"


class ContactoView(TemplateView):
    template_name = "home/contacto.html"
    
    

    

blogMS/templates/home/contacto.html
{% extends "base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mx-auto flex flex-wrap py-6">
    
    <aside class="w-full md:w-1/2 flex flex-col items-center px-3">
        <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <div class="flex flex-col items-center pb-10">
                
                    <img class="w-60 h-36 rounded" src="{% static 'img/logo.png' %}">
              
                <h5 class="mb-1 mt-8 text-md font-medium text-gray-900 dark:text-white">MUJERES SEMBRADORAS INTERNACIONAL</h5>
                <span class="mt-4 text-sm text-gray-500 dark:text-gray-400">Muejres de Reino</span>
                <h5 class="mb-1 mt-4 text-sm font-medium text-gray-400">mujeressembradorasvidanueva@outlook.com</h5>

            </div>
        </div>
    </aside>
    <section class="w-full md:w-2/4 flex flex-col px-3">

        <article class="flex flex-col md:w-full shadow my-4">
            <!-- Article Image -->
            <a class="flex flex-col w-full items-center bg-white md:flex-row md:max-w-xl dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                <img class="object-cover w-full h-96 md:h-auto md:w-28 lg:w-48 ml-6" src="{% static 'img/whatsApp.png' %}" alt="">
                <div class="w-full ml-10 p-4 leading-normal">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">WhatsApp</h5>
                    <hr>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">+1 (321) 978-3033</p>
                </div>
            </a>

            <a class="flex flex-col w-full items-center bg-white md:flex-row md:max-w-xl dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                <img class="object-cover w-full h-96 md:h-auto md:w-28 lg:w-48 ml-6" src="{% static 'img/celular.png' %}" alt="">
                <div class="w-full ml-10 p-4 leading-normal">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Celular</h5>
                    <hr>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">+1 (321) 978-3033</p>
                </div>
            </a>

            <a class="flex flex-col w-full items-center bg-white md:flex-row md:max-w-xl dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                <img class="object-cover w-full h-96 md:h-auto md:w-28 lg:w-48 ml-6" src="{% static 'img/email.png' %}" alt="">
                <div class="w-full ml-10 p-4 leading-normal">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Correo Eléctronico</h5>
                    <hr>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">mujeressembradorasvidanueva@outlook.com</p>
                </div>
            </a>
        </article>
        
      
    </section>
    
        
</div>

<!-- FIN tercer bloque -->
{% include "includes/footer.html" %}

{% endblock content %}

blogMS/templates/home/index.html
<!-- head para PC -->
{% extends "base.html" %}
{% load  static %}

{% block title %}
{{ home.title }}
{% endblock title %}

{% block description %}
<meta name="description" content="{{ home.descripcion }}">
{% endblock description %}

{% block content %}

{% include "includes/header.html" %}



<div class="container mx-auto py-6">
    <section class="grid grid-cols-1 gap-4 md:grid-cols-1 lg:grid-cols-2 shadow-xl mb-8">

        <div class="">
            <img class="w-full p-6" src="{{ portada.image.url }}">
            <h4 class="mt-4 ml-3 font-bold text-2xl"><a href="">{{ portada.title}}</a></h4>
            <p class=" p-4">{{ portada.resume }}</p>
        </div>
     
        <div class="grid grid-cols-1 gap-6 md:grid-cols-1 lg:grid-cols-2 items-center">
            {% for entrada in entradas_home %}
            <div class="">
                <img class="p-6 w-full h-60 items-center" src="{{ entrada.image.url }}">
                <button type="button" 
                class="text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 font-medium rounded-sm text-sm px-5 py-2.5 text-center ml-6 mr-2 mb-2">
                    <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">{{ entrada.title}}</a><!-- ojo modificar la url va a cada articulo de blog-->
                </button>
                
            </div>
            {% endfor %}
            
        </div>
     
     </section>

     
    <section class="grid grid-cols-1 gap-4 md:grid-cols-1 lg:grid-cols-2 shadow-xl mb-8">

        <div class=""><img class="w-full p-6" src="{{ home.image.url }}"></div>
        
        <div class="mt-6 p-6">
            <div class="font-bold text-2xl">{{ home.about_title }}</div>
            <br>
            <div>{{ home.descripcion }}</div>
    
        
            
            <!-- Modal toggle -->
        <div class="mt-72" x-data="{showModal: false}">

            <button @click="showModal = true" 
            class="block text-white mt-4 ml-6 bg-pink-700 hover:bg-pink-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" 
            type="button">Suscribirse
            </button>
    
            <!-- Main modal -->
            <div x-show="showModal" id="authentication-modal" tabindex="-1" aria-hidden="true" class=" flex items-center justify-center fixed top-0 left-0 right-0 z-50 w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative w-full max-w-md max-h-full">
                    <!-- Modal content -->
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <button @click="showModal = false" type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="authentication-modal">
                            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                        <div class="px-6 py-6 lg:px-8">
                            <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Confirma con tu correo electrónico</h3>
                            <form class="" method="POST" action="{% url 'home_app:add-suscripcion' %}">{% csrf_token %}
                                <div class="mb-8">
                                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">ingresa tu correo electrónico</label>
                                    <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="correo@electrónico.com" required>
                                </div>
                                
                                    <button type="submit" class="w-full mt-10 text-white bg-pink-700 hover:bg-pink-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                        enviar
                                    </button>
                                </div>
                                
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </section>

    <!-- Seccion de Cards para ultimas entradas   shadow-xl mb-8"-->
    <section class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-4 shadow-xl  mb-8 bg-gray-100">
        {% for entrada in entradas_recientes %}
        <div class="p-8 border border-gray-200 bg-white">
            <div class="flex items-center">           
                <img src="{{ entrada.image.url }}">
            </div>
     
            <div class="ml-2 p-4">
                <div class="mt-2">
                    <h4 class="font-bold text-2xl"><a href="{% url 'entrada_app:entry-detail' entrada.slug %}">{{ entrada.title}}</a></h4>
                    <p class="mt-4">{{ entrada.resume | truncatechars:100 }}</p> 
                </div>
                
            </div>
        </div>
        {% endfor %}   
     </section>
<!-- div de container -->            
</div>
           
    
<!-- FIN tercer bloque -->
{% include "includes/footer.html" %}

{% endblock content %}

blogMS/templates/home/quienes-somos.html
{% extends "base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

    
<section class="shadow-lg">
    <img src="{% static 'img/banner.jpg' %}" class="w-full">
</section>

<div class="container mx-auto py-6 bg-pink-200">
    <div class="bg-white  text-item-center text-justify">
        <div class="flex flex-col items-center py-12">
            <a class="font-bold text-pink-600 uppercase hover:text-pink-700 text-7xl">
                Visión
            </a>
            <p class="w-1/2 mt-10 text-2xl text-center text-gray-600">
                Formar una comunidad de mujeres restauradas y prosperadas en todas las áreas
                de sus vidas, con la ayuda de Dios, con el voluntariado de otras mujeres y 
                diversas organización de apoyo.
            </p>
        </div>
    </div>
    <hr>
    <br>
    <div class="bg-white  text-item-center text-justify">
        <div class="flex flex-col items-center py-12">
            <a class="font-bold text-pink-600 uppercase hover:text-pink-700 text-7xl">
                Misión
            </a>
            <p class="w-1/2 mt-10 text-2xl text-center text-gray-600">
                Promover eventos de ayuda social a mujeres, con el fin de levantar, restaurar y Formar
                mujeres productivas y prósperas en todas las áreas de su vida.
            </p>
        </div>
    </div>
    <hr>
    <div class="bg-white  text-item-center text-justify">
        <div class="flex flex-col items-center py-12">
            <a class="font-semibold text-gray-500 hover:text-gray-700 text-lg">
               mujeressembradorasvidanueva@outlook.com
            </a>
            
        </div>
    </div>
</div>







<!-- FIN tercer bloque -->
{% include "includes/footer.html" %}

{% endblock content %}