blogMS/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [ 
    path('entradas/', views.EntryListView.as_view(), name='entry-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entry-detail'),  
]

blogMS/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
     path('perfil', views.UserPageView.as_view(), name= 'perfil'),
     path('add-entrada/<pk>', views.AddFavoritosView.as_view(), name= 'add-favoritos'),
     path('delete-favoritos/<pk>', views.FavoritosDeleteView.as_view(), name= 'delete-favoritos'),
    
]

blogMS/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('quienes-somos', views.quienesSomosView.as_view(), name='quienes-somos'),  
    path('contacto', views.ContactoView.as_view(), name='contacto'),  
    path('', views.HomePageView.as_view(), name='index'),  
    path('register-suscripcion', views.SuscribersCreateView.as_view(), name='add-suscripcion'),  
    path('contact', views.contacto, name='add-contact'),   
]

blogMS/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(),name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/',  views.UpdatePasswordView.as_view(), name='user-update'),
]

blogMS/blogMS/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),   
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls de terceros
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] 

if settings.DEBUG:
    urlpatterns_main += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns_main += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns_main += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

# objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}
urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemap.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blogMS/templates/includes/footer.html
{% load static %}

<footer class="bg-pink-400 m-4">
  <div class="flex justify-center">
        
    <div class="flex flex-col">  
      <h3 class="font-semibold text-3xl mt-6">Formulario de Contacto:</h3>
      <form method="POST" action="{% url 'home_app:add-contact' %}">{% csrf_token %}
        <div class="grid md:grid-cols-2 md:gap-6">
          <div class=" w-full my-6 group">
              <input type="text" name="full_name" id="id_full_name" class="block py-2.5 px-0 w-full text-sm text-gray-100 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-pink-400 focus:outline-none focus:ring-0 focus:border-pink-500 peer placeholder-gray-300" placeholder="Nombre" required />
              
          </div>
          <div class=" w-full my-6 group">
            <input type="email" name="email" id="id_email" class="block py-2.5 px-0 w-full text-sm text-gray-100 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-pink-800 focus:outline-none focus:ring-0 focus:border-pink-500 peer placeholder-gray-300" placeholder="Correo electrónico " required />
          </div>
        </div>
        
          <div class=" w-full mb-6 mt-4 group">
              <textarea name="messagge" id="id_messagge" rows="2" class="block py-2.5 px-0 w-full text-sm text-gray-100 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-pink-800 focus:outline-none focus:ring-0 focus:border-pink-500 peer placeholder-gray-300" placeholder="Mensaje " required ></textarea>
          </div>
          
          <button type="submit" class="w-full mt-10 text-white bg-pink-700 hover:bg-pink-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            enviar</button>
        </form>
    </div>
  </div>
  <hr class="mt-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
    <a href="https://etoomtechnology.com/" class="flex justify-center text-sm text-gray-100 sm:text-center hover:underline hover:text-gray-300">www.mujeressembradorasinternacional.com</a>
    <span class="flex justify-center text-sm text-gray-50 sm:text-center">© 2023 Copyright: Mujeres Sembradoras Internacional™</span>
</footer>



        
        

blogMS/templates/includes/header.html
{% load static %}

    
        
    <nav class="w-full py-2 bg-pink-400 shadow">
        <div class="w-full container mx-auto grid grid-cols-1 gap-6 md:grid-cols-1 lg:grid-cols-3 items-center justify-center">
            <div class="text-center">
                <span class="ml-6 text-sm text-gray-100 dark:text-white hover:underline">mujeressembradorasvidanueva@outlook.com</span>
            </div>
        
            <div class="text-center justify-center">
                <a class="text-sm text-gray-100 dark:text-white hover:underline">+1 (321) 978-3033</a>
            </div>
            <div class="text-center justify-between">
                <a class="ml-6 text-gray-800 " href="https://www.facebook.com/profile.php?id=100093439608646">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="ml-6 text-gray-800 " href="https://www.instagram.com/mujeressembradorasintvn">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="ml-6 text-gray-800 " href="#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="ml-6 text-gray-800 " href="#">
                    <i class="fab fa-linkedin"></i>
                </a>
            </div>
        </div>
    </nav>

    <header>
        <div class="w-full container mx-auto flex flex-wrap items-center justify-between">
            <a class="mb-4" href="{% url 'home_app:index' %}">
                <img src="{% static 'img/logo.png' %}"  class="h-16 mx-6 mt-2">
            </a>
            <div class="flex items-center text-sm no-underline mr-6 pr-2">
                {% if request.user.is_authenticated %}
                <a href="{% url 'favoritos_app:perfil' %}" class="text-gray-600 hover:bg-pink-400 hover:text-white rounded py-2 px-2 mx-1">{{user.full_name}}</a>
                {% else %}
                <a href="{% url 'users_app:user-login' %}" class="text-gray-600 hover:bg-pink-400 hover:text-white rounded py-2 px-2 mx-1">Ingresar</a>
                <a href="{% url 'users_app:user-register' %}" class="text-gray-600 hover:bg-pink-400 hover:text-white rounded py-2 px-2 mx-1">Registrarse</a>
                {% endif %}
            </div>
        </div>
    </header>

    <nav class="w-full py-4 bg-pink-600">
        <!--<div class="flex items-center lg:order-2 ml-10">
            <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>-->

        

            <ul class="w-full container mx-auto flex flex-row items-center justify-center lg:text-sm text-xs lg:font-bold font-semibold uppercase mt-0 px-6">
                <li>
                    <a href="{% url 'home_app:index' %}" class="hover:bg-gray-400 rounded py-2 lg:px-2 mx-2" aria-current="page">Inicio</a>
                </li>
                <!--<li>
                    <a href="{% url 'entrada_app:entry-lista' %}" class="hover:bg-gray-400 rounded py-2 px-2 mx-2">Blog</a>
                </li>-->
                <li>
                    <a href="{% url 'entrada_app:entry-lista' %}" class="hover:bg-gray-400 rounded py-2 lg:px-2 mx-2">Blog</a>
                </li>
                <li>
                    <a href="{% url 'home_app:contacto' %}" class="hover:bg-gray-400 rounded py-2 lg:px-2 mxlg:-2">Contacto</a>
                </li>
                <li>
                    <a href="{% url 'home_app:quienes-somos' %}" class="hover:bg-gray-400 rounded py-2 lg:px-2 mx-2">Quienes Somos</a>
                </li>
            </ul>
            <!--<button class="block md:hidden py-3 px-4 mx-2 rounded focus:outline-none hover:bg-gray-200 group">
                <div class="w-5 h-1 bg-gray-600 mb-1"></div>
                <div class="w-5 h-1 bg-gray-600 mb-1"></div>
                <div class="w-5 h-1 bg-gray-600"></div>
                <div class="absolute top-0 -right-full opacity-0 h-screen w8/12 bg-white border transform
                    group-focus:right-0 group-focus:opacity-100 transition-all duration-300">
                    <ul class="flex flex-col items-center w-full text-base cursor-pointer pt-10">
                        <li class="hover:bg-gray-200 py-4 px-6 w-full">Inicio</li>
                        <li class="hover:bg-gray-200 py-4 px-6 w-full">Blog</li>
                        <li class="hover:bg-gray-200 py-4 px-6 w-full">Eventos</li>
                        <li class="hover:bg-gray-200 py-4 px-6 w-full">Contacto</li>
                        <li class="hover:bg-gray-200 py-4 px-6 w-full">Quienes Somos</li>
                    </ul>
                </div>
            </button>-->
        
    </nav>

    <!--<div class="w-full flex-grow sm:flex sm:items-center sm:w-auto ">
            <div class="w-full container mx-auto flex flex-col sm:flex-row items-center justify-center text-sm font-bold uppercase mt-0 px-6 py-2">
                <a href="" class="hover:bg-gray-400 rounded py-2 px-4 mx-2">Inicio</a>
                <a href="" class="hover:bg-gray-400 rounded py-2 px-4 mx-2">Blog</a>
                <a href="" class="hover:bg-gray-400 rounded py-2 px-4 mx-2">Eventos</a>
                <a href="" class="hover:bg-gray-400 rounded py-2 px-4 mx-2">Contactos</a>
                <a href="" class="hover:bg-gray-400 rounded py-2 px-4 mx-2">Quienes Somos</a>
                
            </div>
        </div>-->
   
  
    

  
    
    