blogMS/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [ 
    path('entradas/', views.EntryListView.as_view(), name='entry-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entry-detail'),  
]

blogMS/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
     path('perfil', views.UserPageView.as_view(), name= 'perfil'),
     path('add-entrada/<pk>', views.AddFavoritosView.as_view(), name= 'add-favoritos'),
     path('delete-favoritos/<pk>', views.FavoritosDeleteView.as_view(), name= 'delete-favoritos'),
    
]

blogMS/blogMS/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),   
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls de terceros
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] 

if settings.DEBUG:
    urlpatterns_main += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns_main += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns_main += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

# objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}
urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemap.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blogMS/applications/entrada/models.py
# satandar Library
from datetime import timedelta, datetime
# librerias de django
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
# app de terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from .managers import EntryManager


class Category (TimeStampedModel):
    """ Categorias de una entrada """
    
    short_name = models.CharField('Nombre corto', max_length=60, unique=True)
    name = models.CharField('Nombre', max_length=60, unique=True)
    
 
    
    class Meta():
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
    
    def __str__(self):
        return self.name
    

class Tag(TimeStampedModel):
    """ etiquetas de articulos"""
    
    name = models.CharField('Nombre', max_length=30)
    
    class Meta():
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Tags'
        
    def __str__(self):
        return self.name
    

class Entry(TimeStampedModel):
    """ Modelo de entradas o articulos"""
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    title = models.CharField('Titulo', max_length=200)
    resume = models.TextField('Resumen', blank=True, null=True)
    content = RichTextUploadingField('Contenido', blank=True, null=True)
    publicado = models.DateField('Fecha de Publicacion', blank=True, null=True)
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Entry')
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    slug = models.SlugField(editable=False, max_length=300)
    
    objects = EntryManager()
    
    class Meta():
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse_lazy(
            "entrada_app:entry-detail", 
            kwargs={"slug": self.slug})
    
    
    def save(self, *args, **kwargs):
        # calculamos el total de segundos de la hora actual
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))
        
        self.slug = slugify(slug_unique)
        
        super(Entry, self).save(*args, **kwargs)
        
class Instagram(TimeStampedModel):
    """ Imagenes para Instagram """
    
    name = models.CharField('Nombre', max_length=200)
    public = models.BooleanField(default=False)
    image1 = models.ImageField('Imagen 1', upload_to='Instagram', null=True)
    image2 = models.ImageField('Imagen 2', upload_to='Instagram', null=True)
    image3 = models.ImageField('Imagen 3', upload_to='Instagram', null=True)
    image4 = models.ImageField('Imagen 4', upload_to='Instagram', null=True)
    image5 = models.ImageField('Imagen 5', upload_to='Instagram', null=True)
    image6 = models.ImageField('Imagen 6', upload_to='Instagram', null=True)
    image7 = models.ImageField('Imagen 7', upload_to='Instagram', null=True)
    image8 = models.ImageField('Imagen 8', upload_to='Instagram', null=True)
    image9 = models.ImageField('Imagen 9', upload_to='Instagram', null=True)
   
    
    objects = EntryManager()
    
    class Meta:
        verbose_name = 'Imagen Instagram'
        verbose_name_plural = 'Imagenes Instagram'
        
        def __str__(self):
            return self.name
        
    
    
    
    
        

blogMS/applications/entrada/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from .models import Entry, Category, Instagram


class EntryListView(ListView):
    template_name = "entrada/lista.html"
    context_object_name= 'entradas' # el: context_object_name= es para acceder en ese contexto por el html
    paginate_by = 6
    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context["categorias"] = Category.objects.all()
        
        return context
    
    
    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        categoria = self.request.GET.get("categoria", '') 
        # Consulta de busqueda
        resultado = Entry.objects.buscar_entrada(kword, categoria)
        return resultado
    
class EntryDetailView(DetailView):
    template_name = "entrada/detail.html"
    model = Entry
    
    def get_context_data(self, *args, **kwargs):
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        
        # contexto para los articulos en instagram
        context["instagram"] = Instagram.objects.latest('created')
        
        return context
    
    

blogMS/templates/entrada/detail.html
{% extends "base.html" %}
{% load  static %}

{% block title %}
{{ entry.title }}
{% endblock title %}

{% block description %}
<meta name="description" content="{{ entry.resume }}">
{% endblock description %}

{% block tags %}
<meta name="keywords" content="
    {% for t in entry.tag.all %}
        {{ t.name }},
    {% endfor %}
">
{% endblock tags %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mx-auto flex flex-wrap py-6">

    <!-- Posts Section -->
    <section class="w-full md:w-2/3 flex flex-col items-center px-3">

        <article class="flex flex-col shadow my-4">
            <!-- Article Image -->
            <a href="#" class="hover:opacity-75">
                <img src="{{ entrada.image.url }}">
            </a>
            <div class="bg-white flex flex-col justify-start p-6">
                <a href="#" class="text-blue-700 text-3xl font-bold uppercase pb-4">{{ entry.title}}</a>
                <a href="#" class="text-md hover:text-gray-700 mt-8 pb-4">{{ entry.content | safe}}</a>
                <hr>
                <p class="text-sm pb-3 mt-4">
                    Creado por: <a href="#" class="font-semibold hover:text-gray-800">{{entry.user}}</a> 
                </p>
                <p class="text-sm text-gray-500">Publicado: {{entry.publicado}}</p>
                
            </div>
        </article>

    </section>

    <!-- Sidebar Section -->
    <aside class="w-full md:w-1/3 flex flex-col items-center px-3">

        <div class="w-full bg-white shadow flex flex-col my-4 p-6">
            <div class="w-full items-center"><img src="{{ entry.image.url }}"></div>
            <p class="pb-2 mt-8">{{ entry.resume }}</p>
            <form action="{% url 'favoritos_app:add-favoritos' entry.id %}" method="POST">{% csrf_token %}
                <button type="submit" class=" w-full block text-white bg-pink-700 mt-4 hover:bg-pink-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Agregar a Favoritos
                </button>
            </form>
        </div>

        <div class="w-full bg-white shadow flex flex-col my-4 p-6">
            <p class="text-xl font-semibold pb-5">Instagram</p>
            
            <div class="grid grid-cols-3 gap-3">
                <img class="hover:opacity-75" src="{{ instagram.image1.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image2.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image3.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image4.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image5.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image6.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image7.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image8.url }}">
                <img class="hover:opacity-75" src="{{ instagram.image9.url }}">
            </div>
            <a href="https://www.instagram.com/mujeressembradorasintvn" class="w-full bg-pink-600 text-white font-semibold text-sm rounded hover:bg-pink-700 flex items-center justify-center px-2 py-3 mt-6">
                <i class="fab fa-instagram mr-2"></i> Follow @mujeressembradorasintvn
            </a>
            <a href="https://www.facebook.com/profile.php?id=100093439608646" class="w-full bg-blue-700 text-white font-semibold text-sm rounded hover:bg-blue-600 flex items-center justify-center px-2 py-3 mt-6">
                <i class="fab fa-facebook mr-2"></i> Follow mujeressembradorasintvn
            </a>
        </div>

    </aside>

</div>

<!--<footer class="container mx-auto  w-full border-t bg-white pb-12">
    <div
        class="relative w-full flex items-center invisible md:visible md:pb-12"
        x-data="getCarouselData()"
    >
        <button
            class="absolute bg-blue-800 hover:bg-blue-700 text-white text-2xl font-bold hover:shadow rounded-full w-16 h-16 ml-12"
            x-on:click="decrement()">
            &#8592;
        </button>
        <template x-for="image in images.slice(currentIndex, currentIndex + 6)" :key="images.indexOf(image)">
            <img class="w-1/6 hover:opacity-75" :src="image">
        </template>
        <button
            class="absolute right-0 bg-blue-800 hover:bg-blue-700 text-white text-2xl font-bold hover:shadow rounded-full w-16 h-16 mr-12"
            x-on:click="increment()">
            &#8594;
        </button>
    </div>
    
</footer>

<script>
    function getCarouselData() {
        return {
            currentIndex: 0,
            images: [
                {{ instagram.image1.url }},
                {{ instagram.image2.url }},
                {{ instagram.image3.url }},
                {{ instagram.image4.url }},
                {{ instagram.image5.url }},
                {{ instagram.image6.url }},
                {{ instagram.image7.url }},
                {{ instagram.image8.url }},
                {{ instagram.image9.url }},
            ],
            increment() {
                this.currentIndex = this.currentIndex === this.images.length - 6 ? 0 : this.currentIndex + 1;
            },
            decrement() {
                this.currentIndex = this.currentIndex === this.images.length - 6 ? 0 : this.currentIndex - 1;
            },
        }
    }
</script>-->

<!-- FIN tercer bloque -->
{% include "includes/footer.html" %}

{% endblock content %}

blogMS/templates/entrada/lista.html
<!-- head para PC -->
{% extends "base.html" %}
{% load  static %}


{% block content %}

{% include "includes/header.html" %}

<div class="container mx-auto p-6">
    
    <form class="flex items-center" method="GET">  {% csrf_token %} 
        
        <div class="relative w-full">
            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  </div>
            <input type="text" id="kword" name="kword" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-sm focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Buscar" required>
        </div>
        <button type="submit" class="p-2.5 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
            
        </button>
    </form>


    <section>
        <div class="flex mt-10">
            <ul class="divide-y divide-gray-200 py-8">
                <h2 class="font-bold text-2xl mb-2">Categorias</h2>
                {% for categoria in categorias  %}
                <li class="py-2 text-sm">
                    <a class="hover:underline hover:text-pink-600" href="?categoria={{ categoria.short_name }}">{{ categoria.name }}</a>
                </li>
                {% endfor %}  
            </ul>
          
     
            <div class="p-6 grid grid-cols-1 gap-6 md:grid-cols-1 lg:grid-cols-3 items-center">
                {% for entrada in entradas %}
                <div class="">
                    <img class="p-6 w-full h-60 items-center" src="{{ entrada.image.url }}">
                    <div class="py-4 px-6">
                        <h4 class="font-bold text-2xl"><a href="{% url 'entrada_app:entry-detail' entrada.slug %}">{{ entrada.title}}</a></h4>   
                        <p class="mt-4">{{ entrada.resume | truncatechars:100 }}</p>                                  
                    </div>
                    <a class="py-4 px-6 text-blue-700 font-semibold hover:underline" href="{% url 'entrada_app:entry-detail' entrada.slug %}">leer más...</a> 
                </div>
                {% endfor %}
            </div>
            
        </div>
     
     </section>

     
    <!-- inicio de bloque de paginacion -->
    <section class="mt-8">
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="flex justify-center">
            <ul class="inline-flex -space-x-px">
                {% if page_obj.has_previous  %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}" class="px-3 py-2 ml-2 leading-tight text-gray-800 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"><i class="fas fa-arrow-left mr-2"></i>Anterior</a>
                </li>
                {% endif %}
                
                {% for pagina in paginator.page_range  %}
                {% if pagina == page_obj.number  %}
                <li class="current"><span class="px-3 py-2 ml-2 text-gray-500 bg-white border border-gray-300 hover:bg-blue-500 ">{{pagina}}</li> 
                {% else %}
                <li class=""><a href="?page={{pagina}}" class="px-3 py-2 ml-2 text-gray-500 bg-white border border-gray-300 hover:bg-blue-500 ">{{pagina}}</a></li>
                {% endif %}
                {% endfor %}
                
                
                {% if page_obj.has_next  %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}" class="px-3 py-2 ml-2 text-gray-800">Siguiente<i class="fas fa-arrow-right ml-2"></i></a>
                </li>
                {% endif %}
            </ul>
        </nav>   
        {% endif %}
    </section>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}