blogMS/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [ 
    path('entradas/', views.EntryListView.as_view(), name='entry-lista'),  
    path('entradas/<slug>', views.EntryDetailView.as_view(), name='entry-detail'),  
]

blogMS/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
     path('perfil', views.UserPageView.as_view(), name= 'perfil'),
     path('add-entrada/<pk>', views.AddFavoritosView.as_view(), name= 'add-favoritos'),
     path('delete-favoritos/<pk>', views.FavoritosDeleteView.as_view(), name= 'delete-favoritos'),
    
]

blogMS/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(),name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/',  views.UpdatePasswordView.as_view(), name='user-update'),
]

blogMS/blogMS/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
# seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),   
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls de terceros
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
] 

if settings.DEBUG:
    urlpatterns_main += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns_main += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns_main += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

# objeto site map que genera xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}
urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemap.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blogMS/applications/favoritos/models.py
from django.db import models
from django.conf import settings
# apps de terceros
from model_utils.models import TimeStampedModel
from applications.entrada.models import Entry
from .managers import FavoritesManager


"""class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='user_favorites', on_delete=models.CASCADE)
    #picture = models.ImageField(default='users/user_default_profile.png', upload_to=user_directory_path_profile)

    def __str__(self):
        return f'perfil de{self.user.full_name}'

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
def save_user_profile(sender, instance, **kwargs):
    
    instance.profile.save()
        

# save created profile
post_save.connect(create_user_profile, sender=User)

# save created profile
post_save.connect(save_user_profile, sender=User)"""



class Favorites(TimeStampedModel):
    """ Modelos ara Favoritos """
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_favorites', on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, related_name='entry_favorites', on_delete=models.CASCADE)
    
    objects = FavoritesManager()
    
    class Meta:
        unique_together = ('user', 'entry')
        verbose_name = 'Entrada Favoritas'
        verbose_name_plural = 'Entradas Favoritas'
        
        def __str__(self):
            return self.entry.title
    

    

blogMS/applications/favoritos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, View, DeleteView
from .models import Favorites
from applications.entrada.models import Entry
from django.contrib import messages





class UserPageView(LoginRequiredMixin, ListView):
    template_name = "favoritos/perfil.html"
    context_object_name = 'entradas_user'
    login_url = reverse_lazy('user_app:user-login')
    
    def get_queryset(self):
        return Favorites.objects.entradas_user (self.request.user)
    
class AddFavoritosView(LoginRequiredMixin, View):
    login_url = reverse_lazy('user_app:user-login')
    
    def post(self, request, *args, **kwargs):
        # Recuperar Usuario
        usuario =self.request.user
        entrada = Entry.objects.get(id=self.kwargs['pk'])
        # Registramos favoritos
       
        
        if Favorites.objects.filter(entry=entrada).exists():
            messages.error(request, "Este post ya esta guardado !!!")
            return HttpResponseRedirect(reverse('favoritos_app:perfil'))
        
        elif Favorites.objects.create(user=usuario, entry=entrada):
            
            return HttpResponseRedirect(
                reverse('favoritos_app:perfil')
        )
    
class FavoritosDeleteView(DeleteView):
    model = Favorites
    success_url = reverse_lazy('favoritos_app:perfil')
    

   

blogMS/templates/favoritos/perfil.html
{% extends "base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mx-auto flex flex-wrap py-6">
    
    <aside class="w-full md:w-1/2 flex flex-col items-center px-3">
        <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <div class="flex flex-col items-center pb-10">
                
                    <img class="w-36 h-36 rounded" src="{% static 'img/avatar.jpg' %}">
              
                <h5 class="mb-1 mt-2 text-xl font-medium text-gray-900 dark:text-white">{{ user.full_name }}</h5>
                <span class="text-sm text-gray-500 dark:text-gray-400">{{ user.ocupation}}</span>
                <h5 class="mb-1 text-sm font-medium text-gray-400">{{ user.email }}</h5>
                <div class="flex mt-4 space-x-3 md:mt-6">
                    <a href="{% url 'users_app:user-logout' %}" 
                    class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-pink-600 rounded-lg hover:bg-pink-700 ">
                Cerrar Sesión</a>
                </div>
            </div>
        </div>
    </aside>
    <section class="w-full md:w-2/4 flex flex-col px-3">

        {% for entrada in entradas_user %}
        <article class="flex flex-col md:w-full shadow my-4">
            <!-- Article Image -->
            <a class="flex flex-col w-full items-center bg-white md:flex-row md:max-w-xl dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                <img class="object-cover w-full h-96 md:h-auto md:w-28 lg:w-48 ml-6" src="{{ entrada.entry.image.url }}" alt="">
                <div class="w-full ml-10 p-4 leading-normal">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ entrada.entry.title }}</h5>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ entrada.entry.resume | truncatechars:100 }}</p>
                </div>
            </a>
            <hr>
            <p class="text-sm mt-2 ml-6">
                 <p class="font-sans text-gray-400 ml-4">Creado por: {{entrada.entry.user}}</p> 
            </p>
            <p class="text-sm text-gray-500 ml-4">Publicado {{entrada.entry.publicado}}</p>

            <form class="flex mt-4 space-x-3 md:mt-6" method="POST" action="{% url 'favoritos_app:delete-favoritos' entrada.id %}">{% csrf_token %}
                <a href="{% url 'entrada_app:entry-detail' entrada.entry.id %}" 
                class="inline-flex items-center ml-4 mb-2 px-4 py-2 text-sm font-medium text-center text-white bg-yellow-400 rounded-lg hover:bg-yellow-500 ">
                ver</a>
                <button type="submit" 
                class="inline-flex items-center mb-2 px-4 py-2 text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-700 ">
                Eliminar</button>
            </form>
        
        </article>
        
        {% endfor %}
    </section>
    
        
</div>

<!-- FIN tercer bloque -->
{% include "includes/footer.html" %}

{% endblock content %}